### ISSUE TITLE
Trello::Error: invalid token using Trello.configure

### ISSUE THREAD

**Issue by gs-shahid** [jeremytregunna/ruby-trello#179]
I authenticated a user and got oauth key and secret, then created a client using `Trello::Client.new` and tried `client.find(:board, 'BOARDID') `  THIS WORKED

```
client = Trello::Client.new(
        :consumer_key => ENV['TRELLO_KEY'],
        :consumer_secret => ENV['TRELLO_SECRET'],
        :oauth_token => key,
        :oauth_token_secret => secret
    )
client.find(:board, 'BOARDID') # returns a board
```
BUT Below method did NOT WORKED

I wanted to get list of all boards, I tried `Trello::Board.all` which raised Trello::Error: invalid token 

```
Trello.configure do |config|
      config.consumer_key = ENV['TRELLO_KEY'],
      config.consumer_secret = ENV['TRELLO_SECRET'],
      config.oauth_token = i.token,
      config.oauth_token_secret = i.secret
end

Trello::Board.all # Raised Error

ERROR -- : [400 GET https://api.trello.com/1/members/me]: invalid token
Trello::Error: invalid token
	from /home/gs/.rvm/gems/ruby-2.2.3@camp-one/gems/ruby-trello-1.4.1/lib/trello/client.rb:99:in `invoke_verb'
	from /home/gs/.rvm/gems/ruby-2.2.3@camp-one/gems/ruby-trello-1.4.1/lib/trello/client.rb:19:in `get'
	from /home/gs/.rvm/gems/ruby-2.2.3@camp-one/gems/ruby-trello-1.4.1/lib/trello/client.rb:44:in `find'
	from /home/gs/.rvm/gems/ruby-2.2.3@camp-one/gems/ruby-trello-1.4.1/lib/trello/member.rb:33:in `find'
	from /home/gs/.rvm/gems/ruby-2.2.3@camp-one/gems/ruby-trello-1.4.1/lib/trello/board.rb:56:in `all'
	from (irb):49
	from /home/gs/.rvm/gems/ruby-2.2.3@camp-one/gems/railties-4.2.5/lib/rails/commands/console.rb:110:in `start'
	from /home/gs/.rvm/gems/ruby-2.2.3@camp-one/gems/railties-4.2.5/lib/rails/commands/console.rb:9:in `start'
	from /home/gs/.rvm/gems/ruby-2.2.3@camp-one/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/gs/.rvm/gems/ruby-2.2.3@camp-one/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/gs/.rvm/gems/ruby-2.2.3@camp-one/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/gs/.rvm/gems/ruby-2.2.3@camp-one/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /home/gs/.rvm/gems/ruby-2.2.3@camp-one/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/gs/.rvm/gems/ruby-2.2.3@camp-one/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/gs/.rvm/gems/ruby-2.2.3@camp-one/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /home/gs/camp_one/bin/rails:8:in `<top (required)>'
	from /home/gs/.rvm/gems/ruby-2.2.3@camp-one/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /home/gs/.rvm/gems/ruby-2.2.3@camp-one/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/gs/.rvm/gems/ruby-2.2.3@camp-one/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/gs/.rvm/gems/ruby-2.2.3@camp-one/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /home/gs/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/gs/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'

```

**Comment by gs-shahid** [comment]
My mistake: problem was 'comma' in configure block, It was returning an array of values which caused the issue, I inspected Trello.client and noticed that key was not correctly assigned. 

```
OAuthCredential key=["ba08eb17e38cd9cddea3c97b67138208", "d53d9110bd7dbc1a0ad1b34b8d42e8a937aa135a95de92ad6a2c1acd42b01551", "936840bbb27682f317cb035db14faa5e6bdd2c011715c32332773e28fae08ad8", "49e820cd4f6989f2f4e4e272bc71acb8"]
```

This fixed my problem, configure without any comma at the end.

```
Trello.configure do |config|
      config.consumer_key = ENV['TRELLO_KEY']
      config.consumer_secret = ENV['TRELLO_SECRET']
      config.oauth_token = i.token
      config.oauth_token_secret = i.secret
end
```
