### ISSUE TITLE
rails.cache nil causes undefined method `fetch' for nil:NilClass

### ISSUE THREAD

**Issue by dadamschi** [jeremytregunna/ruby-trello#257]
Not sure what I am missing here. I am trying to run ruby-trello in a rake task using the following (with key and token in place in my code, of course):

`  include Trello
  include Trello::Authorization
  
  Trello.configure do |config|
    config.developer_public_key = " The key from step 1"
    config.member_token = "The token from step 2"
  end

  dadams = Trello::Member.find("me")`

This fails with the following error message:
`Caused by:
NoMethodError: undefined method `fetch' for nil:NilClass
/Users/dadams/.rvm/gems/ruby-2.5.1@myapp/bundler/gems/resolv-robust-9193e4e8d30b/lib/resolv-robust.rb:23:in `get_address_robustly'
/Users/dadams/.rvm/gems/ruby-2.5.1@myapp/bundler/gems/resolv-robust-9193e4e8d30b/lib/resolv-robust-replace.rb:19:in `getaddress'
/Users/dadams/.rvm/gems/ruby-2.5.1@myapp/gems/oauth-0.5.1/lib/oauth/consumer.rb:161:in `request'
/Users/dadams/.rvm/gems/ruby-2.5.1@myapp/gems/oauth-0.5.1/lib/oauth/consumer.rb:195:in `token_request'
/Users/dadams/.rvm/gems/ruby-2.5.1@myapp/gems/oauth-0.5.1/lib/oauth/consumer.rb:136:in `get_request_token'
/Users/dadams/.rvm/gems/ruby-2.5.1@myapp/gems/ruby-trello-2.1.0/lib/trello/authorization.rb:104:in `authorize'
/Users/dadams/.rvm/gems/ruby-2.5.1@myapp/gems/ruby-trello-2.1.0/lib/trello/authorization.rb:77:in `authorize'
/Users/dadams/work/develop/chowly/lib/tasks/rubocop.rake:144:in `block (2 levels) in <top (required)>'
/Users/dadams/.rvm/gems/ruby-2.5.1@myapp/gems/ruby-debug-ide-0.7.0.beta6/lib/ruby-debug-ide.rb:100:in `debug_load'
/Users/dadams/.rvm/gems/ruby-2.5.1@myapp/gems/ruby-debug-ide-0.7.0.beta6/lib/ruby-debug-ide.rb:100:in `debug_program'
/Users/dadams/.rvm/gems/ruby-2.5.1@myapp/gems/ruby-debug-ide-0.7.0.beta6/bin/rdebug-ide:187:in `<main>'
Tasks: TOP => example:get_request_token
(See full trace by running task with --trace)`

Any idea what I am going wrong here? I know for sure the issue is that Rails.cache is not defined but I am noob enough to not know how to resolve that.

**Comment by dadamschi** [comment]
I figured this out by changing to an OAuth example.

`require 'trello'
    require 'yaml'
    require 'resolv-robust'

    include Trello
    include Trello::Authorization

    Trello::Authorization.const_set :AuthPolicy, OAuthPolicy

    CONFIG = YAML::load(File.open("config/trello.yml")) unless defined? CONFIG

    credential = OAuthCredential.new CONFIG['public_key'], CONFIG['private_key']
    OAuthPolicy.consumer_credential = credential

    OAuthPolicy.token = OAuthCredential.new CONFIG['access_token_key'], nil
    Resolv::cache_store = ActiveSupport::Cache::MemoryStore.new

    me = Member.find("me")`

I had to set up the Resolv::cache_store myself.
